name: global-spelling

on:
  pull_request:
    branches: ["master"]

jobs:
  spellcheck:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        with:
          incremental_files_only: false
